export const diseaseConfigs = {
  heart_disease: {
    label: "Heart Disease",
    fields: [
      { name: "age", label: "Age", type: "number", min: 1, max: 100 },
      { name: "sex", label: "Sex (1 = male, 0 = female)", type: "number", min: 0, max: 1 },
      { name: "cp", label: "Chest Pain Type (0-3)", type: "number", min: 0, max: 3 },
      { name: "trestbps", label: "Resting Blood Pressure", type: "number", min: 60, max: 250 },
      { name: "chol", label: "Cholesterol", type: "number", min: 100, max: 600 },
      { name: "fbs", label: "Fasting Blood Sugar > 120 (1/0)", type: "number", min: 0, max: 1 },
      { name: "restecg", label: "Resting ECG (0-2)", type: "number", min: 0, max: 2 },
      { name: "thalach", label: "Max Heart Rate Achieved", type: "number", min: 60, max: 220 },
      { name: "exang", label: "Exercise Induced Angina (1/0)", type: "number", min: 0, max: 1 },
      { name: "oldpeak", label: "ST Depression", type: "number", step: "0.1", min: 0, max: 10 },
      { name: "slope", label: "Slope of Peak Exercise ST (0-2)", type: "number", min: 0, max: 2 },
      { name: "ca", label: "Major Vessels Colored (0-3)", type: "number", min: 0, max: 3 },
      { name: "thal", label: "Thalassemia (1-3)", type: "number", min: 1, max: 3 },
    ],
  },

  diabetes: {
    label: "Diabetes",
    fields: [
      { name: "pregnancies", label: "Pregnancies", type: "number", min: 0, max: 20 },
      { name: "glucose", label: "Glucose", type: "number", min: 0, max: 400 },
      { name: "blood_pressure", label: "Blood Pressure", type: "number", min: 0, max: 200 },
      { name: "skin_thickness", label: "Skin Thickness (mm)", type: "number", min: 0, max: 100 },
      { name: "insulin", label: "Insulin", type: "number", min: 0, max: 900 },
      { name: "bmi", label: "BMI", type: "number", step: "0.1", min: 10, max: 70 },
      { name: "diabetes_pedigree", label: "Diabetes Pedigree Function", type: "number", step: "0.01", min: 0, max: 3 },
      { name: "age", label: "Age", type: "number", min: 1, max: 100 },
    ],
  },

  breast_cancer: {
    label: "Breast Cancer",
    fields: [
      { name: "mean radius", min: 5, max: 30 },
      { name: "mean texture", min: 5, max: 40 },
      { name: "mean perimeter", min: 40, max: 200 },
      { name: "mean area", min: 100, max: 2500 },
      { name: "mean smoothness", min: 0.03, max: 0.2 },
      { name: "mean compactness", min: 0, max: 0.4 },
      { name: "mean concavity", min: 0, max: 0.5 },
      { name: "mean concave points", min: 0, max: 0.3 },
      { name: "mean symmetry", min: 0.1, max: 0.35 },
      { name: "mean fractal dimension", min: 0.04, max: 0.1 },
      { name: "radius error", min: 0, max: 3 },
      { name: "texture error", min: 0, max: 5 },
      { name: "perimeter error", min: 0, max: 25 },
      { name: "area error", min: 0, max: 550 },
      { name: "smoothness error", min: 0, max: 0.03 },
      { name: "compactness error", min: 0, max: 0.15 },
      { name: "concavity error", min: 0, max: 0.4 },
      { name: "concave points error", min: 0, max: 0.05 },
      { name: "symmetry error", min: 0, max: 0.08 },
      { name: "fractal dimension error", min: 0, max: 0.03 },
      { name: "worst radius", min: 7, max: 40 },
      { name: "worst texture", min: 10, max: 50 },
      { name: "worst perimeter", min: 50, max: 260 },
      { name: "worst area", min: 150, max: 4300 },
      { name: "worst smoothness", min: 0.05, max: 0.25 },
      { name: "worst compactness", min: 0, max: 1.1 },
      { name: "worst concavity", min: 0, max: 1.3 },
      { name: "worst concave points", min: 0, max: 0.3 },
      { name: "worst symmetry", min: 0.1, max: 0.7 },
      { name: "worst fractal dimension", min: 0.05, max: 0.2 },
    ].map((f) => ({ ...f, label: f.name, type: "number", step: "0.01" })),
  },

  kidney_disease: {
    label: "Kidney Disease",
    fields: [
      { name: "age", label: "Age", type: "number", min: 1, max: 100 },
      { name: "bp", label: "Blood Pressure", type: "number", min: 40, max: 200 },
      { name: "sg", label: "Specific Gravity", type: "number", step: "0.001", min: 1.0, max: 1.03 },
      { name: "al", label: "Albumin", type: "number", min: 0, max: 5 },
      { name: "su", label: "Sugar", type: "number", min: 0, max: 5 },
      { name: "bgr", label: "Blood Glucose Random", type: "number", min: 0, max: 600 },
      { name: "bu", label: "Blood Urea", type: "number", min: 0, max: 400 },
      { name: "sc", label: "Serum Creatinine", type: "number", step: "0.1", min: 0, max: 40 },
      { name: "sod", label: "Sodium", type: "number", min: 90, max: 170 },
      { name: "pot", label: "Potassium", type: "number", step: "0.1", min: 1, max: 15 },
      { name: "hemo", label: "Hemoglobin", type: "number", step: "0.1", min: 2, max: 20 },
      { name: "pcv", label: "Packed Cell Volume", type: "number", min: 5, max: 60 },
      { name: "wbcc", label: "White Blood Cell Count", type: "number", min: 1000, max: 30000 },
      { name: "rbcc", label: "Red Blood Cell Count", type: "number", step: "0.1", min: 1, max: 8 },
      { name: "rbc_normal", label: "RBC Normal? (1/0)", type: "number", min: 0, max: 1 },
      { name: "pc_normal", label: "Pus Cell Normal? (1/0)", type: "number", min: 0, max: 1 },
      { name: "pcc_present", label: "Pus Cell Clumps Present? (1/0)", type: "number", min: 0, max: 1 },
      { name: "ba_present", label: "Bacteria Present? (1/0)", type: "number", min: 0, max: 1 },
      { name: "htn_yes", label: "Hypertension? (1/0)", type: "number", min: 0, max: 1 },
      { name: "dm_no", label: "Diabetes = No? (1/0)", type: "number", min: 0, max: 1 },
      { name: "dm_yes", label: "Diabetes = Yes? (1/0)", type: "number", min: 0, max: 1 },
      { name: "cad_yes", label: "Coronary Artery Disease? (1/0)", type: "number", min: 0, max: 1 },
      { name: "appet_poor", label: "Poor Appetite? (1/0)", type: "number", min: 0, max: 1 },
      { name: "pe_yes", label: "Pedal Edema? (1/0)", type: "number", min: 0, max: 1 },
      { name: "ane_yes", label: "Anemia? (1/0)", type: "number", min: 0, max: 1 },
    ],
  },

  liver_disease: {
    label: "Liver Disease",
    fields: [
      { name: "Age", label: "Age", type: "number", min: 1, max: 100 },
      { name: "TB", label: "Total Bilirubin", type: "number", step: "0.1", min: 0, max: 75 },
      { name: "DB", label: "Direct Bilirubin", type: "number", step: "0.1", min: 0, max: 20 },
      { name: "Alkphos", label: "Alkaline Phosphotase", type: "number", min: 60, max: 2200 },
      { name: "Sgpt", label: "Sgpt", type: "number", min: 1, max: 2000 },
      { name: "Sgot", label: "Sgot", type: "number", min: 1, max: 5000 },
      { name: "TP", label: "Total Proteins", type: "number", step: "0.1", min: 2, max: 10 },
      { name: "ALB", label: "Albumin", type: "number", step: "0.1", min: 0.5, max: 6 },
      { name: "A/G Ratio", label: "Albumin/Globulin Ratio", type: "number", step: "0.01", min: 0.1, max: 3 },
      { name: "Gender_Male", label: "Gender = Male? (1/0)", type: "number", min: 0, max: 1 },
    ],
  },

  parkinsons: {
    label: "Parkinson's Disease",
    fields: [
      { name: "MDVP:Fo", min: 60, max: 300 },
      { name: "MDVP:Fhi", min: 100, max: 600 },
      { name: "MDVP:Flo", min: 60, max: 250 },
      { name: "MDVP:Jitter", min: 0, max: 0.05 },
      { name: "MDVP:Jitter_1", min: 0, max: 0.001 },
      { name: "MDVP:RAP", min: 0, max: 0.03 },
      { name: "MDVP:PPQ", min: 0, max: 0.03 },
      { name: "Jitter:DDP", min: 0, max: 0.1 },
      { name: "MDVP:Shimmer", min: 0, max: 0.2 },
      { name: "MDVP:Shimmer_1", min: 0, max: 3 },
      { name: "Shimmer:APQ3", min: 0, max: 0.1 },
      { name: "Shimmer:APQ5", min: 0, max: 0.1 },
      { name: "MDVP:APQ", min: 0, max: 0.2 },
      { name: "Shimmer:DDA", min: 0, max: 0.3 },
      { name: "NHR", min: 0, max: 0.5 },
      { name: "HNR", min: 0, max: 40 },
      { name: "RPDE", min: 0, max: 1 },
      { name: "DFA", min: 0.5, max: 1 },
      { name: "spread1", min: -10, max: 0 },
      { name: "spread2", min: 0, max: 1 },
      { name: "D2", min: 0, max: 5 },
      { name: "PPE", min: 0, max: 1 },
    ].map((f) => ({ ...f, label: f.name, type: "number", step: "0.001" })),
  },

  stroke: {
    label: "Stroke",
    fields: [
      { name: "age", label: "Age", type: "number", min: 1, max: 100 },
      { name: "hypertension", label: "Hypertension? (1/0)", type: "number", min: 0, max: 1 },
      { name: "heart_disease", label: "Heart Disease? (1/0)", type: "number", min: 0, max: 1 },
      { name: "avg_glucose_level", label: "Average Glucose Level", type: "number", step: "0.1", min: 40, max: 400 },
      { name: "bmi", label: "BMI", type: "number", step: "0.1", min: 10, max: 70 },
      { name: "gender_Male", label: "Gender = Male? (1/0)", type: "number", min: 0, max: 1 },
      { name: "gender_Other", label: "Gender = Other? (1/0)", type: "number", min: 0, max: 1 },
      { name: "ever_married_Yes", label: "Ever Married? (1/0)", type: "number", min: 0, max: 1 },
      { name: "work_type_Never_worked", label: "Work Type = Never Worked? (1/0)", type: "number", min: 0, max: 1 },
      { name: "work_type_Private", label: "Work Type = Private? (1/0)", type: "number", min: 0, max: 1 },
      { name: "work_type_Self-employed", label: "Work Type = Self-Employed? (1/0)", type: "number", min: 0, max: 1 },
      { name: "work_type_children", label: "Work Type = Child? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Residence_type_Urban", label: "Residence = Urban? (1/0)", type: "number", min: 0, max: 1 },
      { name: "smoking_status_formerly smoked", label: "Formerly Smoked? (1/0)", type: "number", min: 0, max: 1 },
      { name: "smoking_status_never smoked", label: "Never Smoked? (1/0)", type: "number", min: 0, max: 1 },
      { name: "smoking_status_smokes", label: "Currently Smokes? (1/0)", type: "number", min: 0, max: 1 },
    ],
  },

  lung_cancer: {
    label: "Lung Cancer",
    fields: [
      { name: "AGE", label: "Age", type: "number", min: 1, max: 100 },
      { name: "GENDER_Male", label: "Gender = Male? (1/0)", type: "number", min: 0, max: 1 },
      { name: "SMOKING_YES", label: "Smoking? (1/0)", type: "number", min: 0, max: 1 },
      { name: "YELLOW_FINGERS_YES", label: "Yellow Fingers? (1/0)", type: "number", min: 0, max: 1 },
      { name: "ANXIETY_YES", label: "Anxiety? (1/0)", type: "number", min: 0, max: 1 },
      { name: "PEER_PRESSURE_YES", label: "Peer Pressure? (1/0)", type: "number", min: 0, max: 1 },
      { name: "CHRONIC DISEASE_YES", label: "Chronic Disease? (1/0)", type: "number", min: 0, max: 1 },
      { name: "FATIGUE _YES", label: "Fatigue? (1/0)", type: "number", min: 0, max: 1 },
      { name: "ALLERGY _YES", label: "Allergy? (1/0)", type: "number", min: 0, max: 1 },
      { name: "WHEEZING_YES", label: "Wheezing? (1/0)", type: "number", min: 0, max: 1 },
      { name: "ALCOHOL CONSUMING_YES", label: "Alcohol Consuming? (1/0)", type: "number", min: 0, max: 1 },
      { name: "COUGHING_YES", label: "Coughing? (1/0)", type: "number", min: 0, max: 1 },
      { name: "SHORTNESS OF BREATH_YES", label: "Shortness of Breath? (1/0)", type: "number", min: 0, max: 1 },
      { name: "SWALLOWING DIFFICULTY_YES", label: "Swallowing Difficulty? (1/0)", type: "number", min: 0, max: 1 },
      { name: "CHEST PAIN_YES", label: "Chest Pain? (1/0)", type: "number", min: 0, max: 1 },
    ],
  },

  thyroid: {
    label: "Thyroid Disease",
    fields: [
      { name: "age", label: "Age", type: "number", min: 1, max: 100 },
      { name: "TSH", label: "TSH Level", type: "number", step: "0.01", min: 0, max: 100 },
      { name: "T3", label: "T3 Level", type: "number", step: "0.1", min: 0, max: 15 },
      { name: "TT4", label: "TT4 Level", type: "number", min: 0, max: 400 },
      { name: "T4U", label: "T4U Level", type: "number", step: "0.01", min: 0.2, max: 2.5 },
      { name: "FTI", label: "FTI Level", type: "number", min: 0, max: 400 },
      { name: "sex_M", label: "Sex = Male? (1/0)", type: "number", min: 0, max: 1 },
      { name: "on_thyroxine_t", label: "On Thyroxine? (1/0)", type: "number", min: 0, max: 1 },
      { name: "query_on_thyroxine_t", label: "Query On Thyroxine? (1/0)", type: "number", min: 0, max: 1 },
      { name: "on_antithyroid_medication_t", label: "On Antithyroid Medication? (1/0)", type: "number", min: 0, max: 1 },
      { name: "sick_t", label: "Currently Sick? (1/0)", type: "number", min: 0, max: 1 },
      { name: "pregnant_t", label: "Pregnant? (1/0)", type: "number", min: 0, max: 1 },
      { name: "thyroid_surgery_t", label: "Had Thyroid Surgery? (1/0)", type: "number", min: 0, max: 1 },
      { name: "I131_treatment_t", label: "I131 Treatment? (1/0)", type: "number", min: 0, max: 1 },
      { name: "query_hypothyroid_t", label: "Query Hypothyroid? (1/0)", type: "number", min: 0, max: 1 },
      { name: "query_hyperthyroid_t", label: "Query Hyperthyroid? (1/0)", type: "number", min: 0, max: 1 },
      { name: "lithium_t", label: "On Lithium? (1/0)", type: "number", min: 0, max: 1 },
      { name: "goitre_t", label: "Goitre? (1/0)", type: "number", min: 0, max: 1 },
      { name: "tumor_t", label: "Tumor? (1/0)", type: "number", min: 0, max: 1 },
      { name: "hypopituitary_t", label: "Hypopituitary? (1/0)", type: "number", min: 0, max: 1 },
      { name: "psych_t", label: "Psychiatric Condition? (1/0)", type: "number", min: 0, max: 1 },
      { name: "referral_source_SVHC", label: "Referral = SVHC? (1/0)", type: "number", min: 0, max: 1 },
      { name: "referral_source_SVHD", label: "Referral = SVHD? (1/0)", type: "number", min: 0, max: 1 },
      { name: "referral_source_SVI", label: "Referral = SVI? (1/0)", type: "number", min: 0, max: 1 },
      { name: "referral_source_other", label: "Referral = Other? (1/0)", type: "number", min: 0, max: 1 },
    ],
  },

  hepatitis: {
    label: "Hepatitis",
    fields: [
      { name: "Age", label: "Age", type: "number", min: 1, max: 100 },
      { name: "Sex", label: "Sex", type: "number", min: 0, max: 1 },
      { name: "Steroid", label: "Steroid Use? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Antivirals", label: "Antivirals? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Fatigue", label: "Fatigue? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Malaise", label: "Malaise? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Anorexia", label: "Anorexia? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Liver Big", label: "Liver Enlarged? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Liver Firm", label: "Liver Firm? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Spleen Palpable", label: "Spleen Palpable? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Spiders", label: "Spider Angiomata? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Ascites", label: "Ascites? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Varices", label: "Varices? (1/0)", type: "number", min: 0, max: 1 },
      { name: "Bilirubin", label: "Bilirubin", type: "number", step: "0.1", min: 0, max: 75 },
      { name: "Alk Phosphate", label: "Alk Phosphate", type: "number", min: 20, max: 300 },
      { name: "Sgot", label: "Sgot", type: "number", min: 1, max: 500 },
      { name: "Albumin", label: "Albumin", type: "number", step: "0.1", min: 1, max: 6 },
      { name: "Protime", label: "Prothrombin Time", type: "number", step: "0.1", min: 0, max: 100 },
      { name: "Histology", label: "Histology Result? (1/0)", type: "number", min: 0, max: 1 },
    ],
  },
};