export const diseaseConfigs = {
  heart_disease: {
    label: "Heart Disease",
    fields: [
      { name: "age", label: "Age", type: "number" },
      { name: "sex", label: "Sex (1 = male, 0 = female)", type: "number" },
      { name: "cp", label: "Chest Pain Type (0-3)", type: "number" },
      { name: "trestbps", label: "Resting Blood Pressure", type: "number" },
      { name: "chol", label: "Cholesterol", type: "number" },
      { name: "fbs", label: "Fasting Blood Sugar > 120 (1/0)", type: "number" },
      { name: "restecg", label: "Resting ECG (0-2)", type: "number" },
      { name: "thalach", label: "Max Heart Rate Achieved", type: "number" },
      { name: "exang", label: "Exercise Induced Angina (1/0)", type: "number" },
      { name: "oldpeak", label: "ST Depression", type: "number", step: "0.1" },
      { name: "slope", label: "Slope of Peak Exercise ST (0-2)", type: "number" },
      { name: "ca", label: "Major Vessels Colored (0-3)", type: "number" },
      { name: "thal", label: "Thalassemia (1-3)", type: "number" },
    ],
  },

  diabetes: {
    label: "Diabetes",
    fields: [
      { name: "pregnancies", label: "Pregnancies", type: "number" },
      { name: "glucose", label: "Glucose", type: "number" },
      { name: "blood_pressure", label: "Blood Pressure", type: "number" },
      { name: "skin_thickness", label: "Skin Thickness", type: "number" },
      { name: "insulin", label: "Insulin", type: "number" },
      { name: "bmi", label: "BMI", type: "number", step: "0.1" },
      { name: "diabetes_pedigree", label: "Diabetes Pedigree Function", type: "number", step: "0.01" },
      { name: "age", label: "Age", type: "number" },
    ],
  },

  breast_cancer: {
    label: "Breast Cancer",
    fields: [
      "mean radius", "mean texture", "mean perimeter", "mean area", "mean smoothness",
      "mean compactness", "mean concavity", "mean concave points", "mean symmetry", "mean fractal dimension",
      "radius error", "texture error", "perimeter error", "area error", "smoothness error",
      "compactness error", "concavity error", "concave points error", "symmetry error", "fractal dimension error",
      "worst radius", "worst texture", "worst perimeter", "worst area", "worst smoothness",
      "worst compactness", "worst concavity", "worst concave points", "worst symmetry", "worst fractal dimension",
    ].map((name) => ({ name, label: name, type: "number", step: "0.01" })),
  },

  kidney_disease: {
    label: "Kidney Disease",
    fields: [
      { name: "age", label: "Age", type: "number" },
      { name: "bp", label: "Blood Pressure", type: "number" },
      { name: "sg", label: "Specific Gravity", type: "number", step: "0.001" },
      { name: "al", label: "Albumin", type: "number" },
      { name: "su", label: "Sugar", type: "number" },
      { name: "bgr", label: "Blood Glucose Random", type: "number" },
      { name: "bu", label: "Blood Urea", type: "number" },
      { name: "sc", label: "Serum Creatinine", type: "number", step: "0.1" },
      { name: "sod", label: "Sodium", type: "number" },
      { name: "pot", label: "Potassium", type: "number", step: "0.1" },
      { name: "hemo", label: "Hemoglobin", type: "number", step: "0.1" },
      { name: "pcv", label: "Packed Cell Volume", type: "number" },
      { name: "wbcc", label: "White Blood Cell Count", type: "number" },
      { name: "rbcc", label: "Red Blood Cell Count", type: "number", step: "0.1" },
      { name: "rbc_normal", label: "RBC Normal? (1/0)", type: "number" },
      { name: "pc_normal", label: "Pus Cell Normal? (1/0)", type: "number" },
      { name: "pcc_present", label: "Pus Cell Clumps Present? (1/0)", type: "number" },
      { name: "ba_present", label: "Bacteria Present? (1/0)", type: "number" },
      { name: "htn_yes", label: "Hypertension? (1/0)", type: "number" },
      { name: "dm_no", label: "Diabetes = No? (1/0)", type: "number" },
      { name: "dm_yes", label: "Diabetes = Yes? (1/0)", type: "number" },
      { name: "cad_yes", label: "Coronary Artery Disease? (1/0)", type: "number" },
      { name: "appet_poor", label: "Poor Appetite? (1/0)", type: "number" },
      { name: "pe_yes", label: "Pedal Edema? (1/0)", type: "number" },
      { name: "ane_yes", label: "Anemia? (1/0)", type: "number" },
    ],
  },

  liver_disease: {
    label: "Liver Disease",
    fields: [
      { name: "Age", label: "Age", type: "number" },
      { name: "TB", label: "Total Bilirubin", type: "number", step: "0.1" },
      { name: "DB", label: "Direct Bilirubin", type: "number", step: "0.1" },
      { name: "Alkphos", label: "Alkaline Phosphotase", type: "number" },
      { name: "Sgpt", label: "Sgpt", type: "number" },
      { name: "Sgot", label: "Sgot", type: "number" },
      { name: "TP", label: "Total Proteins", type: "number", step: "0.1" },
      { name: "ALB", label: "Albumin", type: "number", step: "0.1" },
      { name: "A/G Ratio", label: "Albumin/Globulin Ratio", type: "number", step: "0.01" },
      { name: "Gender_Male", label: "Gender = Male? (1/0)", type: "number" },
    ],
  },

  parkinsons: {
    label: "Parkinson's Disease",
    fields: [
      "MDVP:Fo", "MDVP:Fhi", "MDVP:Flo", "MDVP:Jitter", "MDVP:Jitter_1", "MDVP:RAP", "MDVP:PPQ",
      "Jitter:DDP", "MDVP:Shimmer", "MDVP:Shimmer_1", "Shimmer:APQ3", "Shimmer:APQ5", "MDVP:APQ",
      "Shimmer:DDA", "NHR", "HNR", "RPDE", "DFA", "spread1", "spread2", "D2", "PPE",
    ].map((name) => ({ name, label: name, type: "number", step: "0.001" })),
  },

  stroke: {
    label: "Stroke",
    fields: [
      { name: "age", label: "Age", type: "number" },
      { name: "hypertension", label: "Hypertension? (1/0)", type: "number" },
      { name: "heart_disease", label: "Heart Disease? (1/0)", type: "number" },
      { name: "avg_glucose_level", label: "Average Glucose Level", type: "number", step: "0.1" },
      { name: "bmi", label: "BMI", type: "number", step: "0.1" },
      { name: "gender_Male", label: "Gender = Male? (1/0)", type: "number" },
      { name: "gender_Other", label: "Gender = Other? (1/0)", type: "number" },
      { name: "ever_married_Yes", label: "Ever Married? (1/0)", type: "number" },
      { name: "work_type_Never_worked", label: "Work Type = Never Worked? (1/0)", type: "number" },
      { name: "work_type_Private", label: "Work Type = Private? (1/0)", type: "number" },
      { name: "work_type_Self-employed", label: "Work Type = Self-Employed? (1/0)", type: "number" },
      { name: "work_type_children", label: "Work Type = Child? (1/0)", type: "number" },
      { name: "Residence_type_Urban", label: "Residence = Urban? (1/0)", type: "number" },
      { name: "smoking_status_formerly smoked", label: "Formerly Smoked? (1/0)", type: "number" },
      { name: "smoking_status_never smoked", label: "Never Smoked? (1/0)", type: "number" },
      { name: "smoking_status_smokes", label: "Currently Smokes? (1/0)", type: "number" },
    ],
  },

  lung_cancer: {
    label: "Lung Cancer",
    fields: [
      { name: "AGE", label: "Age", type: "number" },
      { name: "GENDER_Male", label: "Gender = Male? (1/0)", type: "number" },
      { name: "SMOKING_YES", label: "Smoking? (1/0)", type: "number" },
      { name: "YELLOW_FINGERS_YES", label: "Yellow Fingers? (1/0)", type: "number" },
      { name: "ANXIETY_YES", label: "Anxiety? (1/0)", type: "number" },
      { name: "PEER_PRESSURE_YES", label: "Peer Pressure? (1/0)", type: "number" },
      { name: "CHRONIC DISEASE_YES", label: "Chronic Disease? (1/0)", type: "number" },
      { name: "FATIGUE _YES", label: "Fatigue? (1/0)", type: "number" },
      { name: "ALLERGY _YES", label: "Allergy? (1/0)", type: "number" },
      { name: "WHEEZING_YES", label: "Wheezing? (1/0)", type: "number" },
      { name: "ALCOHOL CONSUMING_YES", label: "Alcohol Consuming? (1/0)", type: "number" },
      { name: "COUGHING_YES", label: "Coughing? (1/0)", type: "number" },
      { name: "SHORTNESS OF BREATH_YES", label: "Shortness of Breath? (1/0)", type: "number" },
      { name: "SWALLOWING DIFFICULTY_YES", label: "Swallowing Difficulty? (1/0)", type: "number" },
      { name: "CHEST PAIN_YES", label: "Chest Pain? (1/0)", type: "number" },
    ],
  },

  thyroid: {
    label: "Thyroid Disease",
    fields: [
      { name: "age", label: "Age", type: "number" },
      { name: "TSH", label: "TSH Level", type: "number", step: "0.01" },
      { name: "T3", label: "T3 Level", type: "number", step: "0.1" },
      { name: "TT4", label: "TT4 Level", type: "number" },
      { name: "T4U", label: "T4U Level", type: "number", step: "0.01" },
      { name: "FTI", label: "FTI Level", type: "number" },
      { name: "sex_M", label: "Sex = Male? (1/0)", type: "number" },
      { name: "on_thyroxine_t", label: "On Thyroxine? (1/0)", type: "number" },
      { name: "query_on_thyroxine_t", label: "Query On Thyroxine? (1/0)", type: "number" },
      { name: "on_antithyroid_medication_t", label: "On Antithyroid Medication? (1/0)", type: "number" },
      { name: "sick_t", label: "Currently Sick? (1/0)", type: "number" },
      { name: "pregnant_t", label: "Pregnant? (1/0)", type: "number" },
      { name: "thyroid_surgery_t", label: "Had Thyroid Surgery? (1/0)", type: "number" },
      { name: "I131_treatment_t", label: "I131 Treatment? (1/0)", type: "number" },
      { name: "query_hypothyroid_t", label: "Query Hypothyroid? (1/0)", type: "number" },
      { name: "query_hyperthyroid_t", label: "Query Hyperthyroid? (1/0)", type: "number" },
      { name: "lithium_t", label: "On Lithium? (1/0)", type: "number" },
      { name: "goitre_t", label: "Goitre? (1/0)", type: "number" },
      { name: "tumor_t", label: "Tumor? (1/0)", type: "number" },
      { name: "hypopituitary_t", label: "Hypopituitary? (1/0)", type: "number" },
      { name: "psych_t", label: "Psychiatric Condition? (1/0)", type: "number" },
      { name: "referral_source_SVHC", label: "Referral = SVHC? (1/0)", type: "number" },
      { name: "referral_source_SVHD", label: "Referral = SVHD? (1/0)", type: "number" },
      { name: "referral_source_SVI", label: "Referral = SVI? (1/0)", type: "number" },
      { name: "referral_source_other", label: "Referral = Other? (1/0)", type: "number" },
    ],
  },

  hepatitis: {
    label: "Hepatitis",
    fields: [
      { name: "Age", label: "Age", type: "number" },
      { name: "Sex", label: "Sex", type: "number" },
      { name: "Steroid", label: "Steroid Use? (1/0)", type: "number" },
      { name: "Antivirals", label: "Antivirals? (1/0)", type: "number" },
      { name: "Fatigue", label: "Fatigue? (1/0)", type: "number" },
      { name: "Malaise", label: "Malaise? (1/0)", type: "number" },
      { name: "Anorexia", label: "Anorexia? (1/0)", type: "number" },
      { name: "Liver Big", label: "Liver Enlarged? (1/0)", type: "number" },
      { name: "Liver Firm", label: "Liver Firm? (1/0)", type: "number" },
      { name: "Spleen Palpable", label: "Spleen Palpable? (1/0)", type: "number" },
      { name: "Spiders", label: "Spider Angiomata? (1/0)", type: "number" },
      { name: "Ascites", label: "Ascites? (1/0)", type: "number" },
      { name: "Varices", label: "Varices? (1/0)", type: "number" },
      { name: "Bilirubin", label: "Bilirubin", type: "number", step: "0.1" },
      { name: "Alk Phosphate", label: "Alk Phosphate", type: "number" },
      { name: "Sgot", label: "Sgot", type: "number" },
      { name: "Albumin", label: "Albumin", type: "number", step: "0.1" },
      { name: "Protime", label: "Prothrombin Time", type: "number", step: "0.1" },
      { name: "Histology", label: "Histology Result? (1/0)", type: "number" },
    ],
  },
};