export const diseaseConfigs = {
  heart_disease: {
    label: "Heart Disease",
    fields: [
      { name: "age", label: "Age", type: "number", min: 29.0, max: 77.0 },
      { name: "sex", label: "Sex (1 = male, 0 = female)", type: "number", min: 0.0, max: 1.0 },
      { name: "cp", label: "Chest Pain Type", type: "number", min: 1.0, max: 4.0 },
      { name: "trestbps", label: "Resting Blood Pressure", type: "number", min: 94.0, max: 200.0 },
      { name: "chol", label: "Cholesterol", type: "number", min: 126.0, max: 564.0 },
      { name: "fbs", label: "Fasting Blood Sugar > 120 (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "restecg", label: "Resting ECG (0-2)", type: "number", min: 0.0, max: 2.0 },
      { name: "thalach", label: "Max Heart Rate Achieved", type: "number", min: 71.0, max: 202.0 },
      { name: "exang", label: "Exercise Induced Angina (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "oldpeak", label: "ST Depression", type: "number", step: "0.1", min: 0.0, max: 6.2 },
      { name: "slope", label: "Slope of Peak Exercise ST", type: "number", min: 1.0, max: 3.0 },
      { name: "ca", label: "Major Vessels Colored", type: "number", min: 0.0, max: 3.0 },
      { name: "thal", label: "Thalassemia", type: "number", min: 3.0, max: 7.0 },
    ],
  },
  diabetes: {
    label: "Diabetes",
    fields: [
      { name: "pregnancies", label: "Pregnancies", type: "number", min: 0.0, max: 17.0 },
      { name: "glucose", label: "Glucose", type: "number", min: 0.0, max: 199.0 },
      { name: "blood_pressure", label: "Blood Pressure", type: "number", min: 0.0, max: 122.0 },
      { name: "skin_thickness", label: "Skin Thickness (mm)", type: "number", min: 0.0, max: 99.0 },
      { name: "insulin", label: "Insulin", type: "number", min: 0.0, max: 846.0 },
      { name: "bmi", label: "BMI", type: "number", step: "0.1", min: 0.0, max: 67.1 },
      { name: "diabetes_pedigree", label: "Diabetes Pedigree Function", type: "number", step: "0.01", min: 0.078, max: 2.42 },
      { name: "age", label: "Age", type: "number", min: 21.0, max: 81.0 },
    ],
  },
  breast_cancer: {
    label: "Breast Cancer",
    fields: [
      { name: "mean radius", label: "mean radius", type: "number", step: "0.01", min: 6.981, max: 28.11 },
      { name: "mean texture", label: "mean texture", type: "number", step: "0.01", min: 9.71, max: 39.28 },
      { name: "mean perimeter", label: "mean perimeter", type: "number", step: "0.01", min: 43.79, max: 188.5 },
      { name: "mean area", label: "mean area", type: "number", step: "0.01", min: 143.5, max: 2501.0 },
      { name: "mean smoothness", label: "mean smoothness", type: "number", step: "0.01", min: 0.05263, max: 0.1634 },
      { name: "mean compactness", label: "mean compactness", type: "number", step: "0.01", min: 0.01938, max: 0.3454 },
      { name: "mean concavity", label: "mean concavity", type: "number", step: "0.01", min: 0.0, max: 0.4268 },
      { name: "mean concave points", label: "mean concave points", type: "number", step: "0.01", min: 0.0, max: 0.2012 },
      { name: "mean symmetry", label: "mean symmetry", type: "number", step: "0.01", min: 0.106, max: 0.304 },
      { name: "mean fractal dimension", label: "mean fractal dimension", type: "number", step: "0.01", min: 0.04996, max: 0.09744 },
      { name: "radius error", label: "radius error", type: "number", step: "0.01", min: 0.1115, max: 2.873 },
      { name: "texture error", label: "texture error", type: "number", step: "0.01", min: 0.3602, max: 4.885 },
      { name: "perimeter error", label: "perimeter error", type: "number", step: "0.01", min: 0.757, max: 21.98 },
      { name: "area error", label: "area error", type: "number", step: "0.01", min: 6.802, max: 542.2 },
      { name: "smoothness error", label: "smoothness error", type: "number", step: "0.01", min: 0.001713, max: 0.03113 },
      { name: "compactness error", label: "compactness error", type: "number", step: "0.01", min: 0.002252, max: 0.1354 },
      { name: "concavity error", label: "concavity error", type: "number", step: "0.01", min: 0.0, max: 0.396 },
      { name: "concave points error", label: "concave points error", type: "number", step: "0.01", min: 0.0, max: 0.05279 },
      { name: "symmetry error", label: "symmetry error", type: "number", step: "0.01", min: 0.007882, max: 0.07895 },
      { name: "fractal dimension error", label: "fractal dimension error", type: "number", step: "0.01", min: 0.0008948, max: 0.02984 },
      { name: "worst radius", label: "worst radius", type: "number", step: "0.01", min: 7.93, max: 36.04 },
      { name: "worst texture", label: "worst texture", type: "number", step: "0.01", min: 12.02, max: 49.54 },
      { name: "worst perimeter", label: "worst perimeter", type: "number", step: "0.01", min: 50.41, max: 251.2 },
      { name: "worst area", label: "worst area", type: "number", step: "0.01", min: 185.2, max: 4254.0 },
      { name: "worst smoothness", label: "worst smoothness", type: "number", step: "0.01", min: 0.07117, max: 0.2226 },
      { name: "worst compactness", label: "worst compactness", type: "number", step: "0.01", min: 0.02729, max: 1.058 },
      { name: "worst concavity", label: "worst concavity", type: "number", step: "0.01", min: 0.0, max: 1.252 },
      { name: "worst concave points", label: "worst concave points", type: "number", step: "0.01", min: 0.0, max: 0.291 },
      { name: "worst symmetry", label: "worst symmetry", type: "number", step: "0.01", min: 0.1565, max: 0.6638 },
      { name: "worst fractal dimension", label: "worst fractal dimension", type: "number", step: "0.01", min: 0.05504, max: 0.2075 },
    ],
  },
  kidney_disease: {
    label: "Kidney Disease",
    fields: [
      { name: "age", label: "Age", type: "number", min: 6.0, max: 90.0 },
      { name: "bp", label: "Blood Pressure", type: "number", min: 50.0, max: 110.0 },
      { name: "sg", label: "Specific Gravity", type: "number", step: "0.001", min: 1.005, max: 1.025 },
      { name: "al", label: "Albumin", type: "number", min: 0.0, max: 4.0 },
      { name: "su", label: "Sugar", type: "number", min: 0.0, max: 5.0 },
      { name: "bgr", label: "Blood Glucose Random", type: "number", min: 70.0, max: 490.0 },
      { name: "bu", label: "Blood Urea", type: "number", min: 10.0, max: 309.0 },
      { name: "sc", label: "Serum Creatinine", type: "number", step: "0.1", min: 0.4, max: 15.2 },
      { name: "sod", label: "Sodium", type: "number", min: 111.0, max: 150.0 },
      { name: "pot", label: "Potassium", type: "number", step: "0.1", min: 2.5, max: 47.0 },
      { name: "hemo", label: "Hemoglobin", type: "number", step: "0.1", min: 3.1, max: 17.8 },
      { name: "pcv", label: "Packed Cell Volume", type: "number", min: 9.0, max: 54.0 },
      { name: "wbcc", label: "White Blood Cell Count", type: "number", min: 3800.0, max: 26400.0 },
      { name: "rbcc", label: "Red Blood Cell Count", type: "number", step: "0.1", min: 2.1, max: 8.0 },
      { name: "rbc_normal", label: "RBC Normal? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "pc_normal", label: "Pus Cell Normal? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "pcc_present", label: "Pus Cell Clumps Present? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "ba_present", label: "Bacteria Present? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "htn_yes", label: "Hypertension? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "dm_no", label: "Diabetes = No? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "dm_yes", label: "Diabetes = Yes? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "cad_yes", label: "Coronary Artery Disease? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "appet_poor", label: "Poor Appetite? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "pe_yes", label: "Pedal Edema? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "ane_yes", label: "Anemia? (1/0)", type: "number", min: 0.0, max: 1.0 },
    ],
  },
  liver_disease: {
    label: "Liver Disease",
    fields: [
      { name: "Age", label: "Age", type: "number", min: 4.0, max: 90.0 },
      { name: "TB", label: "Total Bilirubin", type: "number", step: "0.1", min: 0.4, max: 75.0 },
      { name: "DB", label: "Direct Bilirubin", type: "number", step: "0.1", min: 0.1, max: 19.7 },
      { name: "Alkphos", label: "Alkaline Phosphotase", type: "number", min: 63.0, max: 2110.0 },
      { name: "Sgpt", label: "Sgpt", type: "number", min: 10.0, max: 2000.0 },
      { name: "Sgot", label: "Sgot", type: "number", min: 10.0, max: 4929.0 },
      { name: "TP", label: "Total Proteins", type: "number", step: "0.1", min: 2.7, max: 9.6 },
      { name: "ALB", label: "Albumin", type: "number", step: "0.1", min: 0.9, max: 5.5 },
      { name: "A/G Ratio", label: "Albumin/Globulin Ratio", type: "number", step: "0.01", min: 0.3, max: 2.8 },
      { name: "Gender_Male", label: "Gender = Male? (1/0)", type: "number", min: 0.0, max: 1.0 },
    ],
  },
  parkinsons: {
    label: "Parkinson's Disease",
    fields: [
      { name: "MDVP:Fo", label: "MDVP:Fo", type: "number", step: "0.001", min: 88.333, max: 260.105 },
      { name: "MDVP:Fhi", label: "MDVP:Fhi", type: "number", step: "0.001", min: 102.145, max: 592.03 },
      { name: "MDVP:Flo", label: "MDVP:Flo", type: "number", step: "0.001", min: 65.476, max: 239.17 },
      { name: "MDVP:Jitter", label: "MDVP:Jitter", type: "number", step: "0.001", min: 0.00168, max: 0.03316 },
      { name: "MDVP:Jitter_1", label: "MDVP:Jitter_1", type: "number", step: "0.001", min: 0.00168, max: 0.03316 },
      { name: "MDVP:RAP", label: "MDVP:RAP", type: "number", step: "0.001", min: 0.00068, max: 0.02144 },
      { name: "MDVP:PPQ", label: "MDVP:PPQ", type: "number", step: "0.001", min: 0.00092, max: 0.01958 },
      { name: "Jitter:DDP", label: "Jitter:DDP", type: "number", step: "0.001", min: 0.00204, max: 0.06433 },
      { name: "MDVP:Shimmer", label: "MDVP:Shimmer", type: "number", step: "0.001", min: 0.00954, max: 0.11908 },
      { name: "MDVP:Shimmer_1", label: "MDVP:Shimmer_1", type: "number", step: "0.001", min: 0.00954, max: 0.11908 },
      { name: "Shimmer:APQ3", label: "Shimmer:APQ3", type: "number", step: "0.001", min: 0.00455, max: 0.05647 },
      { name: "Shimmer:APQ5", label: "Shimmer:APQ5", type: "number", step: "0.001", min: 0.0057, max: 0.0794 },
      { name: "MDVP:APQ", label: "MDVP:APQ", type: "number", step: "0.001", min: 0.00719, max: 0.13778 },
      { name: "Shimmer:DDA", label: "Shimmer:DDA", type: "number", step: "0.001", min: 0.01364, max: 0.16942 },
      { name: "NHR", label: "NHR", type: "number", step: "0.001", min: 0.00065, max: 0.31482 },
      { name: "HNR", label: "HNR", type: "number", step: "0.001", min: 8.441, max: 33.047 },
      { name: "RPDE", label: "RPDE", type: "number", step: "0.001", min: 0.25657, max: 0.685151 },
      { name: "DFA", label: "DFA", type: "number", step: "0.001", min: 0.574282, max: 0.825288 },
      { name: "spread1", label: "spread1", type: "number", step: "0.001", min: -7.964984, max: -2.434031 },
      { name: "spread2", label: "spread2", type: "number", step: "0.001", min: 0.006274, max: 0.450493 },
      { name: "D2", label: "D2", type: "number", step: "0.001", min: 1.423287, max: 3.671155 },
      { name: "PPE", label: "PPE", type: "number", step: "0.001", min: 0.044539, max: 0.527367 },
    ],
  },
  stroke: {
    label: "Stroke",
    fields: [
      { name: "age", label: "Age", type: "number", min: 0.08, max: 82.0 },
      { name: "hypertension", label: "Hypertension? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "heart_disease", label: "Heart Disease? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "avg_glucose_level", label: "Average Glucose Level", type: "number", step: "0.1", min: 55.12, max: 271.74 },
      { name: "bmi", label: "BMI", type: "number", step: "0.1", min: 10.3, max: 97.6 },
      { name: "gender_Male", label: "Gender = Male? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "gender_Other", label: "Gender = Other? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "ever_married_Yes", label: "Ever Married? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "work_type_Never_worked", label: "Work Type = Never Worked? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "work_type_Private", label: "Work Type = Private? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "work_type_Self-employed", label: "Work Type = Self-Employed? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "work_type_children", label: "Work Type = Child? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "Residence_type_Urban", label: "Residence = Urban? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "smoking_status_formerly smoked", label: "Formerly Smoked? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "smoking_status_never smoked", label: "Never Smoked? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "smoking_status_smokes", label: "Currently Smokes? (1/0)", type: "number", min: 0.0, max: 1.0 },
    ],
  },
  lung_cancer: {
    label: "Lung Cancer",
    fields: [
      { name: "AGE", label: "Age", type: "number", min: 21.0, max: 87.0 },
      { name: "GENDER_Male", label: "Gender = Male? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "SMOKING_YES", label: "Smoking? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "YELLOW_FINGERS_YES", label: "Yellow Fingers? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "ANXIETY_YES", label: "Anxiety? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "PEER_PRESSURE_YES", label: "Peer Pressure? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "CHRONIC DISEASE_YES", label: "Chronic Disease? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "FATIGUE _YES", label: "Fatigue? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "ALLERGY _YES", label: "Allergy? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "WHEEZING_YES", label: "Wheezing? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "ALCOHOL CONSUMING_YES", label: "Alcohol Consuming? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "COUGHING_YES", label: "Coughing? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "SHORTNESS OF BREATH_YES", label: "Shortness of Breath? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "SWALLOWING DIFFICULTY_YES", label: "Swallowing Difficulty? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "CHEST PAIN_YES", label: "Chest Pain? (1/0)", type: "number", min: 0.0, max: 1.0 },
    ],
  },
  thyroid: {
    label: "Thyroid Disease",
    fields: [
      { name: "age", label: "Age", type: "number", min: 1.0, max: 455.0 },
      { name: "TSH", label: "TSH Level", type: "number", step: "0.01", min: 0.005, max: 530.0 },
      { name: "T3", label: "T3 Level", type: "number", step: "0.1", min: 0.05, max: 10.6 },
      { name: "TT4", label: "TT4 Level", type: "number", min: 2.0, max: 430.0 },
      { name: "T4U", label: "T4U Level", type: "number", step: "0.01", min: 0.25, max: 2.12 },
      { name: "FTI", label: "FTI Level", type: "number", min: 2.0, max: 395.0 },
      { name: "sex_M", label: "Sex = Male? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "on_thyroxine_t", label: "On Thyroxine? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "query_on_thyroxine_t", label: "Query On Thyroxine? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "on_antithyroid_medication_t", label: "On Antithyroid Medication? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "sick_t", label: "Currently Sick? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "pregnant_t", label: "Pregnant? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "thyroid_surgery_t", label: "Had Thyroid Surgery? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "I131_treatment_t", label: "I131 Treatment? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "query_hypothyroid_t", label: "Query Hypothyroid? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "query_hyperthyroid_t", label: "Query Hyperthyroid? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "lithium_t", label: "On Lithium? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "goitre_t", label: "Goitre? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "tumor_t", label: "Tumor? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "hypopituitary_t", label: "Hypopituitary? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "psych_t", label: "Psychiatric Condition? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "referral_source_SVHC", label: "Referral = SVHC? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "referral_source_SVHD", label: "Referral = SVHD? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "referral_source_SVI", label: "Referral = SVI? (1/0)", type: "number", min: 0.0, max: 1.0 },
      { name: "referral_source_other", label: "Referral = Other? (1/0)", type: "number", min: 0.0, max: 1.0 },
    ],
  },
  hepatitis: {
    label: "Hepatitis",
    fields: [
      { name: "Age", label: "Age", type: "number", min: 20.0, max: 72.0 },
      { name: "Sex", label: "Sex", type: "number", min: 1.0, max: 2.0 },
      { name: "Steroid", label: "Steroid Use? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Antivirals", label: "Antivirals? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Fatigue", label: "Fatigue? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Malaise", label: "Malaise? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Anorexia", label: "Anorexia? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Liver Big", label: "Liver Enlarged? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Liver Firm", label: "Liver Firm? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Spleen Palpable", label: "Spleen Palpable? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Spiders", label: "Spider Angiomata? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Ascites", label: "Ascites? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Varices", label: "Varices? (1/0)", type: "number", min: 1.0, max: 2.0 },
      { name: "Bilirubin", label: "Bilirubin", type: "number", step: "0.1", min: 0.3, max: 4.8 },
      { name: "Alk Phosphate", label: "Alk Phosphate", type: "number", min: 26.0, max: 280.0 },
      { name: "Sgot", label: "Sgot", type: "number", min: 14.0, max: 420.0 },
      { name: "Albumin", label: "Albumin", type: "number", step: "0.1", min: 2.1, max: 5.0 },
      { name: "Protime", label: "Prothrombin Time", type: "number", step: "0.1", min: 0.0, max: 100.0 },
      { name: "Histology", label: "Histology Result? (1/0)", type: "number", min: 1.0, max: 2.0 },
    ],
  },
};
