from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_prediction_report(data: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("TitleStyle", parent=styles["Heading1"], textColor=colors.HexColor("#0F3D3E"))
    label_style = ParagraphStyle("LabelStyle", parent=styles["Normal"], textColor=colors.HexColor("#8FA3A0"), fontSize=9)

    elements = []
    elements.append(Paragraph("Clarity Care AI — Assessment Report", title_style))
    elements.append(Spacer(1, 12))

    if "patient_name" in data:
        elements.append(Paragraph(f"Patient: {data['patient_name']}", styles["Normal"]))
    elements.append(Paragraph(f"Disease: {data['predicted_disease'].replace('_', ' ').title()}", styles["Normal"]))
    elements.append(Paragraph(f"Date: {data['created_at']}", styles["Normal"]))
    elements.append(Spacer(1, 16))

    result_text = "Condition Likely Present" if data["prediction"] == 1 else "Condition Unlikely"
    result_color = colors.HexColor("#E76F51") if data["prediction"] == 1 else colors.HexColor("#2A9D8F")
    result_style = ParagraphStyle("ResultStyle", parent=styles["Heading2"], textColor=result_color)
    elements.append(Paragraph(f"Result: {result_text}", result_style))
    elements.append(Paragraph(f"Confidence: {float(data['confidence_score']) * 100:.1f}%", styles["Normal"]))
    elements.append(Spacer(1, 16))

    elements.append(Paragraph("Top Contributing Factors", styles["Heading3"]))
    factor_rows = [["Feature", "Input Value", "Impact"]]
    for item in data["explanation"][:5]:
        impact = "Increases Risk" if item["shap_value"] > 0 else "Decreases Risk"
        factor_rows.append([item["feature"], str(item["input_value"]), impact])

    table = Table(factor_rows, colWidths=[2.2 * inch, 1.5 * inch, 2 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F3D3E")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E0E0E0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F7F5")]),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 24))

    disclaimer_style = ParagraphStyle("Disclaimer", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#8FA3A0"))
    elements.append(Paragraph(
        "This report is generated by a machine learning model and is intended for informational "
        "purposes only. It does not constitute medical advice or a diagnosis. Please consult a "
        "qualified healthcare professional for any health concerns.",
        disclaimer_style,
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()